name: Integration
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build_and_upload_artifact_for_linux_with_tls:
    name: Build and Upload Artifact for linux with tls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for linux
        run: |
          sudo apt-get install -y ninja-build
      - name: Download mbedtls Linux Release
        run: |
          wget https://github.com/ilkerhalil/mbedtls/releases/download/v3.0.9/mbedtls-linux.tar.gz
          wget https://github.com/ilkerhalil/mbedtls/releases/download/v3.0.9/mbedtls-headers.tar.gz
      - name: Extract mbedtls
        run: |
          mkdir -p /tmp/mbedtls
          tar -xvf mbedtls-headers.tar.gz -C /tmp/mbedtls
          tar -xvf mbedtls-linux.tar.gz -C /tmp/mbedtls
      - name: Build nng with tls
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON \
          -DNNG_ENABLE_TLS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ELIDE_DEPRECATED=ON \
          -DNNG_TOOLS=OFF \
          -DMBEDTLS_ROOT_DIR=/tmp/mbedtls \
          ..
          cmake --build . --config Release
      - name: Test nng with tls
        run: ctest --output-on-failure -C "Release"
        working-directory: build
      - name: Create Artifact For nng with tls
        run: |
          mkdir -p nng-linux
          cp build/libnng.so nng-linux
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-linux-with-tls
          path: |
            nng-linux/
  build_and_upload_artifact_for_linux:
    name: Build and Upload Artifact for linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for linux
        run: |
          sudo apt-get install -y ninja-build
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ELIDE_DEPRECATED=ON \
          -DNNG_TOOLS=OFF \
          ..
          cmake --build . --config Release
      - name: Test nng
        run: ctest --output-on-failure -C "Release"
        working-directory: build
      - name: Create Artifact For nng
        run: |
          mkdir -p nng-linux
          cp build/libnng.so nng-linux
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-linux
          path: |
            nng-linux/
  build_and_upload_artifact_for_macos_with_tls:
    name: Build and Upload Artifact for macos with tls
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for macos
        run: |
          brew install ninja
      - name: Download mbedtls Macos Release
        run: |
          wget https://github.com/ilkerhalil/mbedtls/releases/download/v3.1.0/mbedtls-macos.tar.gz
          wget https://github.com/ilkerhalil/mbedtls/releases/download/v3.1.0/mbedtls-headers.tar.gz
      - name: Extract mbedtls
        run: |
          mkdir -p /tmp/mbedtls
          tar -xvf mbedtls-headers.tar.gz -C /tmp/mbedtls
          tar -xvf mbedtls-macos.tar.gz -C /tmp/mbedtls
      - name: Build nng with tls
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON \
          -DNNG_ENABLE_TLS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ELIDE_DEPRECATED=ON \
          -DNNG_TOOLS=OFF \
          -DMBEDTLS_ROOT_DIR=/tmp/mbedtls \
          ..
          cmake --build . --config Release
      - name: Test nng with tls
        run: ctest --output-on-failure -C "Release"
        working-directory: build
      - name: Create Artifact For nng with tls
        run: |
          mkdir -p nng-macos
          cp build/libnng.so nng-macos
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-macos-with-tls
          path: |
            nng-macos/
  build_and_upload_artifact_for_macos:
    name: Build and Upload Artifact for macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for macos
        run: |
          brew install ninja
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ELIDE_DEPRECATED=ON \
          -DNNG_TOOLS=OFF \
          ..
          cmake --build . --config Release
      - name: Test nng
        run: ctest --output-on-failure -C "Release"
        working-directory: build
      - name: Create Artifact For nng
        run: |
          mkdir -p nng-macos
          cp build/libnng.so nng-macos
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-macos
          path: |
            nng-macos/
  build_and_upload_artifact_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build nng
        shell: bash
        run: |
          cmake -B build
          cmake --build build
      - name: Test nng
        run: |
          ctest -C Debug --output-on-failure
        working-directory: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-win
          path: |
            build/Debug/nng.lib
            include/