name: Integration
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build_and_upload_artifact_for_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for linux
        run: |
          sudo apt-get install -y libmbedtls-dev ninja-build
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ENABLE_TLS=ON \
          ..
          ninja
      - name: Test nng
        run: ctest --output-on-failure
        working-directory: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-linux
          path: |
            build/libnng.a
            include/
  build_and_upload_artifact_for_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for macos
        run: |
          brew install mbedtls ninja
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ENABLE_TLS=ON \
          ..
          ninja
      - name: Test nng
        run: ctest --output-on-failure
        working-directory: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-macos
          path: |
            build/libnng.a
            include/
  build_and_upload_artifact_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build nng
        shell: bash
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Test nng
        run: |
          ctest -C Release --output-on-failure
        working-directory: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-macos
          path: |
            build/Release/nng.lib
            include/