name: Integration
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build_and_upload_artifact_for_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for linux
        run: |
          sudo apt-get install -y libmbedtls-dev ninja-build
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ENABLE_TLS=ON \
          ..
          ninja
      - name: Test
        run: ctest --output-on-
        working-directory: build
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-${{ matrix.config.name }}
          path: |
            build/libnng.a
            include/
  build_and_upload_artifact_for_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies for macos
        run: |
          brew install mbedtls ninja
      - name: Build nng
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DNNG_ENABLE_TLS=ON \
          ..
          ninja
      - name: Test
        run: ctest --output-on-
        working-directory: build
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nng-${{ matrix.config.name }}
          path: |
            build/libnng.a
            include/