name: darwin
on:
  push:
    paths-ignore: ["docs/**", "**.adoc", "**.md"]
  pull_request:
    paths-ignore: ["docs/**", "**.adoc", "**.md"]
jobs:
  build:
    name: build
    runs-on: [macos-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Mbed TLS
        run: brew install mbedtls

      - name: Install ninja
        run: brew install ninja

      - name: Configure
        run: mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DNNG_ENABLE_TLS=ON ..

      - name: build
        run: cd build && ninja

      - name: Test
        run: cd build && ctest --output-on-failure
